abstract: A Textile formatter for Kwiki.
author: Kang-min Liu <gugod@gugod.org>.
build_requires: 
  Test::Base: 0
distribution_type: module
generated_by: Module::Install version 0.60
license: perl
name: Kwiki-Textile
no_index: 
  directory: 
    - inc
    - t
requires: 
  Kwiki: 0.38
  perl: 5.6.1
version: 0.01
